Add mobile Nav Page
frempongdev/Personal-Portfolio pull request #13
Opened 2023-01-03 13:00 UTC by frempongdev

In this Pull Request, I made the following Changes :

- Added the Mobile Navigation Pop-Up Page.
- - Edited index.html to accommodate dynamic changes to mobile page.
- - Added complimentary style classes to style.css file.
- - Added script.js file with function to create dynamic elements.
- - Made changes to correct Linter Errors.

2023-01-03 14:07 UTC, prolajumokeoni commented
Hi @Team 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has lighthouse  linter errors please fix it

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-03 14:28 UTC, frempongdev commented
@prolajumokeoni , thank you for your feedback.

Is there a way I can solve the liters error since we have tried all we can?

2023-01-03 16:10 UTC, jerryowusu requested changes
Hi Team :wave: , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost-paul-walker](https://user-images.githubusercontent.com/65233860/210393397-0d8e0562-b6aa-4ea9-8f4b-0a39848790a2.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Close button working as expected :heavy_check_mark: 
Followed GitHub flow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-03 16:10 UTC, jerryowusu commented on style.css
> +  }
There are some slight differences between the menu items and that of the figma design as indicated below :point_down: . Kindly check the position, margin, and size and ensure that they match the figma design. 

### Your design

![Screenshot from 2023-01-03 15-54-11](https://user-images.githubusercontent.com/65233860/210394779-91ee22f9-23d5-4a6f-9c06-b6097cc13f3e.png)


### Figma design 

![Screenshot from 2023-01-03 15-54-18](https://user-images.githubusercontent.com/65233860/210394795-ae128337-94ed-4f91-97b6-a3ef35dce42b.png)

2023-01-03 16:10 UTC, jerryowusu commented on style.css
> +  }
The menu is supposed to be an overlay and not scrollable, however, your mobile nav menu is not fixed hence can be scrolled and dissappear from the screen. This does not give a good user experience. Kindly ensure that you fix this to match the figma design and achieve standard best practices. :wink: 

### Your design when scrolled

![Screenshot from 2023-01-03 15-54-52](https://user-images.githubusercontent.com/65233860/210395549-c0bbd57c-67c5-44e2-b854-35099ba37d2c.png)


### Figma design 

![Screenshot from 2023-01-03 15-54-18](https://user-images.githubusercontent.com/65233860/210395584-4584dc4e-0c0d-42db-b8de-bc763bd5bdf6.png)

2023-01-04 10:09 UTC, jerryowusu approved these changes
Hi @frempongdev , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![yeasss](https://user-images.githubusercontent.com/65233860/210532026-e3789211-be29-497c-aea3-7b8c59e4c0b1.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 10:27 UTC, merged