Add desktop version
frempongdev/Personal-Portfolio pull request #7
Opened 2022-12-14 20:52 UTC by frempongdev

In this Pull request, I made the following changes :
- Added Style and Changes to complete Desktop version.
- - Added a new screen query for Desktop.
- - Updated CSS file to fit Desktop query.
- - Edited HTML file to adjust additional desktop files.
- - Ensured strict linter guidelines.

2022-12-15 18:00 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @frempongdev 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 18:30 UTC, frempongdev commented on style.css
> +    height: 100%;
Kindly give me the screen size that shows this unwrapped section of the page. 
It seems to be working fine on all my screens.

2022-12-16 08:34 UTC, Abenezer-Tilahun commented on index.html
>            <li><a href="#">About</a></li>
Fixed.

2022-12-16 08:35 UTC, Abenezer-Tilahun commented on index.html
> +              <!-- <a href="#">See Project</a> -->
Fixed.

2022-12-16 08:55 UTC, Abenezer-Tilahun approved these changes
Hi @frempongdev 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️Good Job  Implement the desktop version with the usage of media queries.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 08:55 UTC, Abenezer-Tilahun commented on index.html
> +                <h4 class="grey-text desktop-text">Full Stack Dev</h4>
- [ optional ] As suggested by the previous reviewer Kindly make this text in one line and not broken in 2 lines to improve readability and to follow the design in Figma 💯.



The Figma design Look likes this  : 

![Capture](https://user-images.githubusercontent.com/93598189/208060595-627cedfb-822a-4986-ad3b-aba63301fe42.PNG)


Your Design Look likes this : 

![Capture](https://user-images.githubusercontent.com/93598189/208059521-2c83e245-274b-4dec-b039-b04da524617d.PNG)

2022-12-16 08:55 UTC, Abenezer-Tilahun commented on style.css
> +    height: 100%;
Fixed.

2022-12-16 09:40 UTC, merged